// <auto-generated />
namespace MVCClub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Oneclubwith2membersand2events : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Oneclubwith2membersand2events));
        
        string IMigrationMetadata.Id
        {
            get { return "201907201253023_One club with 2 members and 2 events"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
