// <auto-generated />
namespace MVCClub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Applicationuserfieldsadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Applicationuserfieldsadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201907200701083_Application user fields added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
