// <auto-generated />
namespace MVCClub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _2moreclubsseeded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2moreclubsseeded));
        
        string IMigrationMetadata.Id
        {
            get { return "201907201303446_2 more clubs seeded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
